oxhild_user:
    resource: "@OxhildUserBundle/Resources/config/routing.yml"
    prefix:   /

oxhild_import:
    resource: "@OxhildImportBundle/Resources/config/routing.yml"
    prefix:   /

oxhild_mtg:
    resource: "@OxhildMtgBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"