oxhild_user:
    resource: "@OxhildUserBundle/Resources/config/routing.yml"
    prefix:   /

oxhild_mtg:
    resource: "@OxhildMtgBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"