oxhild_homepage:
    path:     /
    defaults: { _controller: OxhildMtgBundle:Default:index }

oxhild_search_card:
    path:     /search/{name}
    defaults: { _controller: OxhildMtgBundle:Default:search }
