<?php

namespace Oxhild\MtgBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Oxhild\MtgBundle\Entity\BinderCard;

/**
 * BinderCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BinderCardRepository extends EntityRepository
{
    public function getCardsByBinder($id)
    {
        $entities = $this->getEntityManager()
            ->getRepository('OxhildMtgBundle:BinderCard')
            ->createQueryBuilder('q')
            ->select('q')
            ->where('q.binder = :binder')
            ->orderBy('q.card', 'ASC')
            ->setParameter('binder', $id)
            ->getQuery()
            ->getResult();

        if ($entities == null) {
            return false;
        }

        $cards = [];

        foreach ($entities as $entity) {
            $cards[] = $entity->getCard();
        }

        return $cards;
    }

    public function addCardToBinder($card, $binder)
    {
        $em = $this->getEntityManager();

        $card = $this->$em->getRepository('OxhildMtgBundle:Card')
            ->find($card);
        $binder = $em->getRepository('OxhildMtgBundle:Binder')
            ->find($binder);

        $compare = $em->getRepository('OxhildMtgBundle:BinderCard')
            ->createQueryBuilder('r')
            ->select('r')
            ->where('r.binder = :binder')
            ->andWhere('r.card = :card')
            ->setParameter('card', $card)
            ->setParameter('binder', $binder)
            ->getQuery()
            ->getOneOrNullResult();

        if ($compare == null) {
            $add = new BinderCard();
            $add->setCard($card);
            $add->setBinder($card);
            $em->persist($add);
            $em->flush();
        } else {
            $compare->addCount();
            $em->persist($compare);
            $em->flush();
        }
    }

    public function removeCardFromBinder($card, $binder)
    {
        $em = $this->getEntityManager();
        $card = $this->$em->getRepository('OxhildMtgBundle:Card')
            ->find($card);
        $binder = $em->getRepository('OxhildMtgBundle:Binder')
            ->find($binder);

    }
}
