<?php

namespace Oxhild\MtgBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BinderCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BinderRepository extends EntityRepository
{

}
