<?php

namespace Oxhild\MtgBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BinderCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BinderCardRepository extends EntityRepository
{
    public function getCardsByBinder($id)
    {
        $entities = $this->getEntityManager()
            ->getRepository('OxhildMtgBundle:BinderCard')
            ->createQueryBuilder('q')
            ->select('q')
            ->where('q.binder = :binder')
            ->orderBy('q.card', 'ASC')
            ->setParameter('binder', $id)
            ->getQuery()
            ->getResult();

        if ($entities == null) {
            return false;
        }

        $cards = [];

        foreach ($entities as $entity) {
            $cards[] = $entity->getCard();
        }

        return $cards;
    }
}
